### ISSUE TITLE
the last.pth may be broken.

### ISSUE THREAD

**Issue by xiaominli1020** [littlepure2333/MindBridge#4]
hello, when loading state_dict to the optimizer, I got "KeyError('param_groups')", I am not sure if the ckpt is broken. Could you plz check it?
![image](https://github.com/littlepure2333/MindBridge/assets/25433111/e001d708-f36d-4824-92a1-29b140a084fe)

**Comment by littlepure2333** [comment]
Hi, may I ask what command are you using to launch the code?

**Comment by littlepure2333** [comment]
Hi, I understand the issue you're encountering when trying to resume training with the `--resume` option. I have revised the code to address this bug. The problem was related to the [DeepSpeed](https://huggingface.co/docs/accelerate/usage_guides/deepspeed) library used in this project for reducing memory occupation. DeepSpeed partitions optimizer states, so the code for saving and resuming needed to be adjusted accordingly.

Additionally, if you only want to load the pre-trained weights and start training, you can use the `--load_from` option instead of `--resume`. The `--resume` option requires additional saved states during training to correctly restore the optimizer states, which I did not upload to Huggingface. The checkpoint I uploaded only contains the valid pre-trained weights.

Hope this helps :)
